name: Update Google Analytics Credentials

on:
  # 允许手动触发来更新凭证
  workflow_dispatch:

# 设置权限
permissions:
  contents: read
  actions: read

jobs:
  update-credentials:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        pip install google-analytics-data google-auth
        
    - name: Verify GA credentials
      env:
        GA_CREDENTIALS: ${{ secrets.GA_CREDENTIALS }}
      run: |
        echo "$GA_CREDENTIALS" > service-account-key.json
        export GOOGLE_APPLICATION_CREDENTIALS=service-account-key.json
        python verify-setup.py
        echo "✅ GA凭证验证成功"
